### ISSUE TITLE
Game crashes when pressing 1.

### ISSUE THREAD

**Issue by jelleejamm** [FigmentBoy/DialogHandler#2]

**Comment by FigmentBoy** [comment]
If the json does not exist for a number, the dialog won't be handled

**Comment by FigmentBoy** [comment]
It's been a while with no response so I'm going to close this. Basically just make sure you follow the instructions in the README, and try just copying the example into `1.json` to test it.

**Comment by CoderQCYT** [comment]
doesnt work for me

**Comment by uNaMEdUsER-BmTH** [comment]
same

**Comment by uNaMEdUsER-BmTH** [comment]
it just crashes

**Comment by CoderQCYT** [comment]
got it to work
